packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@max-null/dsh-memory@0.2.2'
  - '@max-null/dsh-node-appearance@0.1.1'
  - '@max-null/dsh-chat-rail@0.1.0'
  - '@max-null/dsh-chinese-thinking@0.2.0'
  - '@max-null/dsh-guardian@0.1.0'
  - '@max-null/dsh-habit@0.1.0'
  - '@max-null/dsh-plugin-center@0.1.4'
  - '@max-null/dsh-plugin-center@0.1.6'
  - '@max-null/dsh-memory@0.3.7'
  - '@max-null/dsh-chat-rail@0.1.2'
  - 'dsh-better-sidebar@0.14.0'
  - '@max-null/dsh-memory@0.3.8'
  - '@max-null/dsh-plugin-center@0.1.7'
  - dsh-better-sidebar@0.13.1
  - dsh-better-sidebar@0.12.3
  - dsh-excel-panel@0.3.2
  - dsh-sidebar-qa@0.1.0
  - dsh-video-preview@0.1.1
  - '@max-null/dsh-skill-mcp-center@0.2.0'
  - '@huanlin/dsh-plugin-better-sidebar-plugin-office@0.1.0'
allowBuilds:
  node-pty: false
  koffi: true
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  protobufjs: true



